-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 10, 2021 at 08:22 AM
-- Server version: 10.4.20-MariaDB
-- PHP Version: 8.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `newsproject`
--

-- --------------------------------------------------------

--
-- Table structure for table `berita`
--

CREATE TABLE `berita` (
  `id` varchar(255) NOT NULL,
  `judul` varchar(100) DEFAULT NULL,
  `kategori` char(10) NOT NULL,
  `penulis` varchar(25) DEFAULT NULL,
  `konten` varchar(5000) DEFAULT NULL,
  `tanggal` date DEFAULT NULL,
  `gambar` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `berita`
--

INSERT INTO `berita` (`id`, `judul`, `kategori`, `penulis`, `konten`, `tanggal`, `gambar`) VALUES
('616177a87cf1c', 'Egy Maulana Dicintai Pendukung FK Senica ', 'olahraga', 'banu', 'Jakarta, CNN Indonesia -- Direktur Olahraga FK Senica, David Balda, mengatakan Egy Maulana Vikri mendapat sambutan positif dari pendukung klub Liga Slovakia Fortuna Liga tersebut. Meski baru bergabung dengan FK Senica dan hanya dikontrak enam bulan, Egy mampu mendapat perhatian pendukung klub asal Slovakia tersebut. Balda mengatakan Egy dicintai pendukung FK Senica. Jumlah penggemar FK Senica, dikatakan Balda, meningkat sejak pemain timnas Indonesia itu bergabung.', '2021-10-01', 'https://akcdn.detik.net.id/visual/2021/09/28/egy-maulana-vikri-2_169.jpeg?w=650'),
('616179ff561c0', 'Baim Wong-Paula Verhoeven Dikaruniai Anak Kedua', 'hiburan', 'alex', 'Jakarta, CNN Indonesia -- Selebritas sekaligus youtuber Baim Wong menyambut kelahiran putra keduanya pada Sabtu (9/10). Kabar ini diketahui dari Instagram Dr. I Gusti Ayu Nyoman Partiwi atau biasa disapa dokter Tiwi, yang mendampingi istri Baim, Paula Verhoeven, saat melahirkan. Tiwi mengunggah video singkat Baim Wong saat menggendong anak keduanya.  Sementara Baim lewat Instagramnya mengatakan anak keduanya itu lahir dalam keadaan sehat. ', '2021-10-25', 'https://akcdn.detik.net.id/visual/2021/10/09/baim-wong-dan-paula-verhoeven_169.jpeg?w=650'),
('61619b2d3fd0f', 'Rangkuman Covid: Cemas Klaster PON hingga Geser Libur Maulid', 'nasional', 'wayan', 'Jakarta, CNN Indonesia -- Penambahan kasus covid-19 menurun selama 11 pekan terakhir. Sejumlah daerah mulai melaporkan tidak ada penambahan kasus kematian.\r\nTingkat keterisian tempat tidur atau bed occupancy rate (BOR) turut melandai. Namun, ancaman potensi gelombang ketiga covid-19 tetap ada, apalagi menjelang libur Natal dan Tahun baru.\r\n\r\nCNNIndonesia.com telah merangkum peristiwa dan informasi perihal perkembangan kasus Covid-19 di Indonesia dalam 24 jam terakhir, sebagaimana berikut.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/10/05/bali-rebut-emas-beregu-campuran-judo-pon-papua_169.jpeg?w=650'),
('61619bc42572a', 'Desakan Menguat, Jokowi Diminta Kumpulkan Parpol Bahas Pemilu', 'politik', 'niko', ' Jakarta, CNN Indonesia -- Gerindra, PPP dan PKS setuju dengan usulan agar Presiden Joko Widodo mengadakan pertemuan dengan partai politik guna membahas jadwal pemungutan suara Pemilu dan Pilkada Serentak 2024.Hingga saat ini, partai politik, KPU serta pemerintah masih memiliki opsi masing-masing, sehingga belum ada kesepakatan bulat.Sekjen Gerindra Ahmad Muzani yakin pertemuan antara Presiden Jokowi dengan parpol bisa menjembatani perbedaan pandangan yang ada.', '2021-10-12', 'https://akcdn.detik.net.id/visual/2021/08/10/joko-widodo_169.jpeg?w=650'),
('61619c51d038a', 'Goodbye dari Dolar AS Tak Semudah Membalikkan Telapak Tangan', 'ekonomi', 'jonathan', ' Jakarta, CNN Indonesia -- Indonesia dan beberapa negara Asia mulai putar haluan, meninggalkan penggunaan dolar AS dalam transaksi perdagangan internasional. Lewat perjanjian Local Currency Settlement (LCS), transaksi perdagangan internasional akan diselesaikan dengan mata uang lokal masing-masing negara. Tidak melulu dolar AS seperti sebelumnya.\r\nKebijakan antar bank sentral ini pertama kali dimulai oleh Bank Indonesia (BI) dengan Malaysia pada 2018 lalu. Transaksi bilateral kedua negara dilakukan dengan rupiah dan ringgit.\r\n\r\nDisusul, penggunaan mata uang yen Jepang dan baht Thailand yang resmi dipakai pada 2020 dan diikuti oleh RI-China pada September 2021 lalu.\r\nTak sampai di situ, Gubernur BI Perry Warjiyo mengatakan saat ini sedang menjajaki perluasan LCS dengan dua negara ASEAN lainnya, yaitu Singapura dan Filipina.\r\n\r\nMenurut dia, penggunaan mata uang lokal antara Indonesia dengan sejumlah negara mitra dagang perlu dilakukan demi efisiensi. Terlebih, hubungan RI dengan negara terkait menyangkut masalah aliran investasi. Selain itu, LCS dinilai bisa berdampak pada stabilisasi pasar keuangan masing-masing negara karena ketergantungan terhadap dolar AS terus berkurang.\r\n\r\nKepala Ekonom Bank Permata Josua Pardede mengamini pernyataan Perry tersebut. Josua menilai banyak manfaat implementasi LCS. Pertama, tentunya, efisiensi biaya kuotasi untuk nasabah atau pengusaha.\r\n\r\nDengan menggunakan mata uang lokal, maka biaya transaksi bakal lebih murah. Bila sebelumnya perlu dilakukan kuotasi dua kali dari rupiah-dolar AS dan dolar AS ke mata uang lokal setempat, maka kini kuotasi hanya sekali saja.\r\n', '2021-10-25', 'https://akcdn.detik.net.id/visual/2018/06/29/64740496-91b1-4ffa-a014-5ae9973db91c_169.jpeg?w=650'),
('61619da9a92f7', 'Mayoritas Uang Kripto Melemah, Binance Coin Sampai Bitcoin', 'bisnis', 'christine', ' Jakarta, CNN Indonesia -- Mayoritas uang kripto melaju di zona merah pada Sabtu (9/10) pagi. Terlihat, dari 10 aset kripto dengan kapitalisasi tertinggi, binance coin (BNB) melemah cukup dalam mencapai 3,98 persen dalam 24 jam terakhir.\r\nMengutip coinmarket.com, harga binance coin bertengger di level US$423,71 per keping. Saat ini, nilai kapitalisasi pasar binance coin sebesar US$70,88 miliar.\r\n\r\nPelemahan diikuti oleh cardano (ADA) sebesar 2,01 persen dalam 24 jam terakhir menjadi US$2,25 per keping. Namun, jika dilihat dalam sepekan terakhir, harga cardano menguat 0,28 persen.\r\n\r\n\r\nKemudian, polkadot (DOT) tampak melemah 1,78 persen dalam 24 jam terakhir menjadi US$33,41 per keping. Begitu juga dengan dogecoin (DOGE) yang melemah 0,38 persen dalam 24 jam terakhir ke level Rp0,24 per keping.', '2021-10-30', 'https://akcdn.detik.net.id/visual/2021/05/14/ilustrasi-bitcoin-1_169.jpeg?w=650'),
('61624f2fc74cb', '8 Debutan Timnas Indonesia U-23 di Kualifikasi Pia', 'olahraga', 'Stronkman', ' Jakarta, CNN Indonesia -- Dari 33 nama yang dipanggil untuk memperkuat Timnas Indonesia U-23 di Kualifikasi Piala Asia 2022, delapan di antaranya merupakan pemain debutan.\r\nMenurut jadwal, Kualifikasi Piala Asia U-23 2022 akan digelar di Tajikistan pada 27 Oktober hingga 2 November mendatang. Timnas Indonesia berada di grup G bersama Australia dan China setelah Brunei Darussalam memutuskan untuk mengundurkan diri.\r\n\r\nDari nama-nama yang dipanggil, beberapa di antaranya merupakan wajah-wajah baru hasil pantauan dari Shin Tae Yong di kompetisi Liga 1 dan Liga 2 yang sudah bergulir. Beberapa nama lain merupakan pemain yang sebelumnya pernah dipanggil dan atau telah memperkuat Timnas Indonesia U-19.\r\n\r\nBerikut debutan Timnas U-23 untuk Kualifikasi Piala Asia:\r\n\r\n1. Rabbani Tasnim Siddiq (Borneo FC)\r\n\r\nRabbani merupakan striker kelahiran 26 Mei 2003. Total ia sudah enam kali tampil bersama Borneo FC sejak bergabung pada 2020 lalu.\r\n\r\nDebutnya di Borneo terjadi pada 22 Maret 2021 di turnamen pra musim Piala Presiden. Saat itu Borneo FC kalah 0-1 dari Bhayangkara FC. Di kompetisi Liga 1 2021/2022, Rabbani sudah dua kali dimainkan, yakni ketika melawan Bali United dengan hasil imbang 1-1 pada 28 September dan menghadapi Persita Tangerang 2 Oktober lalu.\r\n\r\nMeski belum mencetak gol, penampilan jebolan Aqua Danone Nations Cup 2015 itu ternyata cukup menarik perhatian Shin Tae Yong.\r\n\r\n2. Ronaldo Joybera Kwateh (Madura United)\r\n\r\nUsia Ronaldo Kwateh atau yang dikenal dengan Ronaldo Junior masih 16 tahun. Ia menjadi salah satu pemain termuda yang tampil di Liga 1 2021/2022.\r\n\r\nPemanggilan Ronaldo Kwateh ke Timnas Indonesia sebenarnya bukan jadi kali pertama. Sebelumnya ia juga pernah mendapat panggilan Timnas Indonesia U-16 arahan Bima Sakti.\r\n', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/02/10/latihan-perdana-timnas-u-22-1_169.jpeg?w=650'),
('61624fb9b02eb', 'Polisi Tangkap Tersangka Otak Kerusuhan di Yahukim', 'nasional', 'Klein Watson', ' Jakarta, CNN Indonesia -- Polisi pada Sabtu (9/10) ini menangkap Morume Keya Busup, tersangka insiden penyerangan suku Yali di Yahukimo, Papua, yang terjadi awal Oktober lalu.\r\nKadivhumas Mabes Polri, Irjen Pol Argo Yuwono mengatakan, Morumen sebelumnya telah masuk daftar pencarian orang (DPO) oleh pihak kepolisian. Ia ditangkap Sabtu hari ini, atau sepekan usai kerusuhan, oleh aparat gabungan dari Polres Yahukimo dan Satgas Nemangkawi.\r\n\r\n\"Ditangkap hari Sabtu tanggal 9 Oktober 2021 Pukul 03.40 WIT, bertempat di jalan Gunung Distrik Dekai, Kabupaten Yahukimo,\" kata Argo dalam keterangannya.\r\n\r\nArgo menjelaskan, Morume Keya Busup merupakan Kepala suku Umum Kimyal, yang menyerang suku Yali pada Minggu (3/10). Bersama pelaku, polisi turut mengamankan sejumlah barang bukti berupa satu buah busur, sembilan anak panah, satu buah kampak, satu unit ponsel, perangkat elektronik dan identitas diri lain milik tersangka.\r\n\r\nSelain Morume, aparat juga mengamankan satu tersangka lain atas nama Beto Ordias. Keduanya dibawa ke Polres Yahukimo untuk kemudian diselidiki lebih mendalam.\r\n\r\n\"Kasus tersebut telah ditangani oleh Polres Yahukimo,\" katanya.\r\n\r\nKericuhan di Distrik Dekai, Yahukimo, Papua terjadi pada Minggu (3/10) lalu, dengan melibatkan dua kelompok massa dari dua suku berbeda: Suku Kimyal dan Suku Yali.\r\n\r\nUsai insiden itu, polisi mengamankan sedikitnya 52 orang terduga pelaku penyerangan. Polisi juga kemudian menetapkan 22 orang sebagai tersangka.\r\n\r\nInsiden ricuh di Yahukimo telah menyebabkan 41 orang luka-luka dan enam orang dipastikan meninggal dunia.\r\n\r\nMenurut polisi, ricuh itu dipicu kabar simpang siur alasan meninggalnya mantan Bupati Yahukimo, Abock Busup saat tugas ke Jakarta. Abock ditemukan tak sadar diri di kamar Hotel Grand Mercure, Jakarta Pusat.\r\n\r\nPihak Kepolisian menegaskan bahwa tidak ada tanda-tanda kekerasan maupun obat-obatan. Abock lantas dibawa ke RS Meilia Cibubur sekitar pukul 11.00 WIB, namun tak tertolong.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2018/08/31/2ae3c978-4069-41f9-a855-734e9ce558c1_169.jpeg?w=650'),
('616250312fd44', 'Djoko Susanto, Bandar Kelontong Modern Alfamart', 'ekonomi', 'Want Riches', ' Jakarta, CNN Indonesia -- Ibu-ibu rumah tangga tak perlu khawatir kehabisan tepung saat memasak. Begitu pula, bapak-bapak yang candu menghisap rokok. Ada Alfamart, ritel modern, yang hadir di setiap pengkolan jalan. Di balik setiap gerai mini market yang jumlahnya bejibun itu, ada nama Djoko Susanto sang pendiri dan CEO Alfamart.\r\nNama Djoko Susanto mungkin tidak seakrab pengusaha-pengusaha kakap di Indonesia, seperti Hartono bersaudara, Mochtar Riady dan keluarga, Dato Sri Tahir, atawa Jerry Ng. Namun, Djoko Susanto masuk dalam daftar 50 orang terkaya di Indonesia.\r\n\r\nMenurut Forbes, kekayaan Djoko Susanto mencapai US$2,3 miliar atau setara Rp32,7 triliun (kurs Rp14.250 per dolar AS) pada 8 Oktober 2021.\r\n\r\nKekayaannya sedikit menurun, tetapi posisinya tercatat sebagai orang terkaya ke-19 di Indonesia. Naik dari tahun 2019 di urutan ke-20.\r\n\r\nDjoko Susanto lahir dengan nama Kwok Kwie Fo pada 9 Februari 1950. Ia adalah anak keenam dari 10 bersaudara.\r\n\r\nTidak seperti pengusaha sukses pada umumnya yang berhasil menyelesaikan studi hingga tingkat tertinggi, Djoko Susanto harus putus sekolah.\r\n\r\nPada usia 17 tahun, ia sudah mulai mengelola usaha milik orang tuanya, kios yang menjual bahan-bahan makanan dan rokok di Pasar Arjuna, Jakarta.\r\n\r\nKeduanya pun menjalin kerja sama dan sepakat mengawali 15 kios di beberapa lokasi di Jakarta. Pada 27 Agustus 1989, lahirlah Alfa Toko Gudang Rabat dengan konsep mini market.\r\n\r\nAlfa Toko Gudang Rabat inilah yang kemudian menjadi cikal bakal kesuksesan Djoko Susanto sebagai bos Alfamart dan Alfamidi yang gerainya mudah ditemukan sejauh mata memandang.\r\n\r\nIa melanjutkan kemitraan dengan Putera Sampoerna hingga 2005, sampai lambat laun mengambil bagian terbesar dari Alfa dan mengembangkannya di bawah merek Alfa di bawah pengelolaan PT Sumber Alfaria Trijaya Tbk.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/10/06/taipan-djoko-susanto_169.jpeg?w=650'),
('6162534eb0666', 'Stafsus Erick Thohir Tanggapi Anggaran Kereta Cepat Bengkak', 'bisnis', '', ' Jakarta, CNN Indonesia -- Staf Khusus Menteri BUMN Arya Sinulingga mengungkap pembengkakan anggaran dalam pembangunan proyek kereta cepat Jakarta-Bandung adalah hal yang wajar.\r\nArya mengungkap pembengkakan anggaran terjadi karena ada perubahan desain. Lagi pula, menurut dia, perubahan anggaran bukan hal baru. Dalam beberapa proyek infrastruktur seperti pembangunan jalan tol, kenaikan anggaran juga kerap terjadi.\r\n\r\n\"Pembengkakan itu hal yang wajar. Namanya pembangunan awal dan sebagainya, itu membuat hal yang jadi agak terhambat. Jadi, di mana-mana juga kemunduran yang sebelumnya itu akan menaikkan cost,\" papar Arya dalam keterangan resmi, Sabtu (9/10).\r\n\r\nArya membantah bahwa kenaikan anggaran tersebut telah direncanakan. Menurut dia, pembengkakan terjadi karena menyesuaikan kondisi geologis dan geografis.\r\n\r\nKenaikan harga tanah misalnya. Menurut dia, sejak proyek itu dimulai pada 2016, kenaikan harga tanah adalah sesuatu yang tidak bisa dihindarkan.\r\n\r\n\"Ada kenaikan harga. Itu wajar terjadi. Di hampir semua pembangunan yg kita lakukan, sejak dulu itu pasti ada perubahan-perubahan di sana yang membuat pembengkakan anggaran,\" katanya.\r\n\r\nArya menambahkan perubahan anggaran dalam lanjutan pembangunan kereta api cepat Jakarta-Bandung tak lain supaya proyek yang telah mencapai 80 persen tersebut dapat diselesaikan.\r\n\r\n\r\nSejumlah perusahaan yang tergabung dalam konsorsium proyek kereta cepat mengalami kondisi keuangan yang buruk. Mulai dari Wijaya Karya, PTPN, maupun Jasa Marga. Lagi pula, katanya, kondisi itu bukan hanya terjadi di Indonesia. Keterlibatan pemerintah dalam setiap pembangunan proyek kereta cepat juga dialami banyak negara.\r\n\r\n\"Jadi, hanya kemaren karena masalah corona ini yang membuat semuanya jadi terhambat. Jadi jangan dipelintir ini ada hal-hal lain dan sebagainya,\" kata dia.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2020/03/09/ba84ef60-6f1f-4440-ab5f-102d414da372_169.jpeg?w=650'),
('616255e1d9c5c', 'Dirawat di RS, Kondisi Dorce Gamalama Dikabarkan Membaik', 'hiburan', 'Klaudius', ' Jakarta, CNN Indonesia -- Dorce Gamalama sempat tidak sadarkan diri dan dibawa ke rumah sakit. Namun kabar terakhir menyebut seniman senior ini kondisinya sudah membaik.\r\nHetty Sunjaya, kerabat dekat Dorce, mengatakan dirinya diberitahu keluarga bahwa Dorce sudah bisa diajak bicara. Tak sekadar respons singkat, Dorce kini sudah bisa mengobrol dengan keluarganya.\r\n\r\n\"Sudah bisa ngobrol, sudah enakan dan jauh lebih baik alhamdulillah. Sudah bisa bicara, oke,\" kata Hetty melalui pesan teks pada Sabtu (9/10), seperti dikutip dari detik.\r\n\r\nSebelumnya kabar Dorce dilarikan ke RS berasal dari status WhatsApp (WA) Mimi, keponakan Dorce. Melalui status WA, Mimi menyebut Dorce dalam kondisi tidak sadarkan diri dan dirawat di ICU.\r\n\r\nHanya saja, Dorce memang sebelumnya sudah dirawat di RS sejak beberapa waktu lalu. Dalam tayangan Kopi Viral, Mimi mengatakan Dorce sempat tidak bisa bangun dari tempat tidur sehingga harus dirawat di RS. Karena sudah membaik, ia pun boleh pulang.\r\n\r\nSepulang dari RS, kondisinya memang membaik. Namun keesokan harinya, Dorce tidak merespons saat dibangunkan kala Ashar.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/10/08/dorce-gamalama-2_169.jpeg?w=650'),
('61625637663d3', 'MUI: Vaksin Zifivax Asal China Halal', 'nasional', 'Carol', ' Jakarta, CNN Indonesia -- Majelis Ulama Indonesia (MUI) menyatakan vaksin virus Covid-19 dengan merek Zifivax halal untuk digunakan. Vaksin tersebut diproduksi perusahaan China Anhui Zhifei Longcom Biopharmaceutical Co., Ltd.\r\nPernyataan itu tertuang dalam fatwa MUI Nomor 53 Tahun 2021 tentang produk vaksin covid-19 dari Anhui Zhifei Longcom Biopharmaceutical Co., Ltd.\r\n\r\n\"Vaksin Covid-19 produksi Anhui Zhifei Longcom Biopharmaceutical Co., Ltd. hukumnya suci dan halal,\" bunyi fatwa tersebut dikutip CNNIndonesia.com, Minggu (10/10).\r\n\r\nKeputusan itu diambil setelah MUI menimbang beberapa hal. Salah satu pertimbangannya adalah vaksinasi sebagai upaya untuk menghadapi Covid-19.\r\n\r\n\"Wabah Covid-19 masih menjadi ancaman kesehatan, dan di antara ikhtiar untuk mencegah terjadinya penularan wabah\r\ntersebut adalah melalui vaksinasi,\" tulisnya.\r\n\r\nSelain itu, MUI juga menerima permintaan sertifikasi halal terhadap produk vaksin tersebut, mengingat produk obat dan vaksin yang akan dikonsumsi oleh umat\r\nIslam wajib diperhatikan dan diyakini kesucian dan kehalalannya.\r\n\r\n\"Ada permohonan sertifikasi halal terhadap produk vaksin Covid-19 dari Anhui Zhifei Longcom Biopharmaceutical Co., Ltd,\" ungkapnya.\r\n\r\nMUI menyatakan, fatwa ini mulai berlaku pada tanggal ditetapkan yaitu 28 September 2021. Namun, kata MUI jika di kemudian hari ternyata terdapat kekeliruan, akan diperbaiki dan disempurnakan sebagaimana mestinya.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/09/07/ilustrasi-vaksin-1_169.jpeg?w=650'),
('6162576b48062', 'Adele Bocorkan Lagu ke Fan Lewat Instagram Live', 'hiburan', 'Illona', 'Adele yang live dari Los Angeles membuka live instagram dengan menjawab pertanyaan dari para penggemarnya. Berdasarkan pantauan CNNIndonesia.com, ada sekitar 120 ribu orang yang bergabung dalam IG live tersebut.\r\n\r\nBahkan penyanyi Alicia Keys pun salah satu yang menonton IG Live tersebut. Ketika cuplikan lagu baru tersebut diperdengarkan, Alicia Keys sempat berkomentar.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/10/08/adele-2_169.jpeg?w=650'),
('616258ff6d464', 'RI Terancam Tak Boleh Gelar Kejuaraan Olahraga, Atlet Juga Terimbas ', 'olahraga', 'Crazy Foot', ' Jakarta - Indonesia terancam tak bisa menggelar kejuaraan internasional baik tingkat regional, kontinental, maupun dunia, menyusul pernyataan dari Badan Antidoping Dunia (WADA).\r\nWADA menyatakan Indonesia tidak patuh dalam penegakan standar antidoping, sehingga tidak memenuhi syarat untuk menjadi tuan rumah kejuaraan tingkat regional, kontinental, atau internasional, selama masa penangguhan.\r\n\r\nSelain Indonesia, WADA juga memasukkan Korea Utara dan Thailand dalam daftar negara yang tidak patuh. Hal itu disampaikan WADA dalam sebuah pernyataan yang dilansir Reuters.\r\n\r\nDisebutkan bahwa Badan Anti-Doping Nasional di Korea Utara dan Indonesia tidak patuh karena tidak menerapkan program pengujian yang efektif. Sedangkan Thailand gagal untuk sepenuhnya menerapkan kode atau standar prosedur antidoping yang ditetapkan WADA.\r\n\r\nIndonesia, Thailand, dan Korea Utara dinyatakan tidak berhak menjadi tuan rumah kejuaraan regional hingga dunia selama penangguhan, selain juga tidak memenuhi syarat untuk duduk sebagai anggota dewan di komite.\r\n\r\nAtlet dari ketiga negara masih diperbolehkan ikut pertandingan-pertandingan di kejuaraan regional, kontinental, dan dunia tapi tidak diperbolehkan membawa nama dan mengibarkan bendera negara selain di ajang Olimpiade.\r\n\r\nSampai berita ini diturunkan, belum ada kabar pasti kapan sanksi itu mulai diterapkan oleh WADA. Jika terjadi, maka bisa saja Indonesia gagal menggelar ajang-ajang internasional di rumah sendiri. Seperti FIBA Asia Cup 2022 atau MotoGP Indonesia pada 2022 mendatang.\r\n\r\nSementara di multievent seperti SEA Games 2022 dan Asian Games 2022, Merah Putih terancam tak bisa berkibar walaupun ada atlet Indonesia yang meraih medali, terkait dengan sanksi WADA.', '2021-10-10', 'https://akcdn.detik.net.id/community/media/visual/2021/05/02/ilustrasi-bendera-indonesia-1_169.jpeg?w=700&q=90'),
('616259981a925', 'IHSG Ditutup Naik 1,02 Persen Berkat Aksi Beli Investor Asing Rp2,41 Triliun', 'bisnis', 'Dwi Nicken Fari', ' Bisnis.com, JAKARTA - Indeks Harga Saham Gabungan (IHSG) ditutup menguat pada akhir perdagangan pekan ini. Berdasarkan data Bloomberg, indeks komposit ditutup naik 1,02 persen menjadi 6.481 pada akhir perdagangan Jumat (8/10/2021). Sepekan terakhir, IHSG terapresiasi 4,06 persen. Pada perdagangan hari ini sebanyak 299 saham menguat, 209 saham melemah, dan 152 saham stagnan.\r\n\r\nNilai beli investor asing di seluruh pasar mencapai Rp2,41 triliun. Saham PT Bank Rakyat Indonesia (Persero) Tbk. menjadi salah satu saham yang paling banyak dibeli investor asing senilai Rp518,12 miliar. Harga BBRI pun menguat 0,97 persen menjadi Rp4.160. Selanjutnya saham PT Bank Central Asia Tbk. juga banyak dibeli asing senilai Rp540,60 miliar dan harga BBCA menguat 1,82 persen menjadi Rp36.450.', '2021-10-10', 'https://images.bisnis-cdn.com/thumb/posts/2021/10/08/1452112/hil-bursa-1.jpg?w=744&h=465'),
('61625a3ca7c97', 'Ridwan Kamil Ungkap Rencana Tawarkan Kawasan Rebana ke Asing', 'ekonomi', 'Tugas Men', ' Jakarta, CNN Indonesia -- Dua kawasan industri di Metropolitan Rebana akan ditawarkan kepada investor Timur Tengah. Gubernur Jawa Barat M Ridwan Kamil mengungkap hal ini saat bertemu dengan Menteri BUMN Erick Thohir serta Dirut PT PP dan PT Angkasa Pura di Gedung Negara Pakuan, Bandung.\r\nRidwan mengatakan pertemuan tersebut membahas sejumlah rencana penguatan investasi di Jabar.\r\n\r\nRebana Metropolitan merupakan wilayah utara/timur laut Provinsi Jabar yang meliputi tujuh daerah, yakni Kabupaten Sumedang, Majalengka, Cirebon, Subang, Indramayu, dan Kuningan, serta Kota Cirebon.\r\n\r\nDua kawasan industri Rebana yang akan ditawarkan ke investor Timur Tengah adalah pengembangan aerocity di Majalengka dan investasi di bekas tanah PT RNI di Subang.\r\n\r\n\"Mayoritas di Rebana yaitu di Subang di lahan bekas PT RNI dan di aerocity akan kami sosialisasikan di Timur Tengah,\" ungkap Emil dikutip dari Antara, Minggu (10/10).\r\n\r\nPromosi dua kawasan Rebana tersebut masuk dalam agenda pemerintah pusat yaitu safari investasi yang akan dilakukan dalam waktu dekat.\r\n\r\n\"Kebetulan pemerintah pusat berencana akan safari investasi di Abu Dhabi, di mana salah satu agendanya adalah mempromosikan investasi di kawasan Rebana,\" kata Emil.\r\n\r\nDalam safari investasi ke Timur Tengah tersebut, Emil akan turut hadir bersama Erick Thohir karena ada keterkaitan dengan perusahaan milik BUMN.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/03/30/gubernur-jawa-barat-ridwan-kamil_169.jpeg?w=650'),
('61625adb7fd30', 'Partai Pelopor Ganti Nama Jadi Partai Perkasa', 'politik', 'Wehey Hey', ' Pergantian nama itu telah diputuskan dalam Kongres Partai yang digelar di Hotel Acacia, Jakarta Pusat pada Sabtu (9/10).\r\n\r\n\"Pergantian nama Partai Pelopor ke Partai Perkasa merupakan keputusan kongres selajutnya tentu sesuai agenda akan ada perubahan AD/ART serta pemilihan pengurus Partai Perkasa,\" kata Ketua Panitia Kongres Ristiyanto dalam keterangannya, Sabtu (9/10).\r\n\r\n\"Setelah berganti nama dari partai Pelopor ke Partai Perkasa tentunya agenda kami selanjutnya yakni mengadakan kongres pertama Partai Perkasa menjelang pemilu 2024,\" kata dia.\r\n\r\nPartai Pelopor sebelumnya didirikan oleh Rachmawati pada Agustus 2002. Kini partai tersebut dipimpin Eko Suryo Santjojo, Ristiyanto sebagai Sekretaris Jenderal.\r\n\r\nDalam pidatinya, Eko ingin Partai Pelopor tidak lagi bicara sebagai partai nasionalis, namun harus memiliki ceruk lebih luas dan segmentasi yang lebih jelas. Ia ingin partainya menyesuaikan diri dengan perkembangan zaman, dan tidak terjebak dalam dikotomi SARA yang berpotensi mendegradasi situasi politik nasional.\r\n\r\n\"Labeling cebong, kampret dan kadrun jelas telah merusak tatanan politik nasional akibat idiom nasionalisme dan relijius. ini merupakan prodak industri demokrasi yang menciptakan buzzer-buzzer bayaran yang prilakunya jauh dari nilai-nilai Pancasila,\" kata dia.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/10/06/ilustrasi-dokumen-investigasi_169.jpeg?w=650'),
('61625b39010c9', 'Wagub DKI Buka Suara Soal Dugaan Anies Dijegal Maju 2024', 'politik', 'Wow Amazia', ' Riza irit bicara saat ditanya ihwal tudingan itu. Menurut dia, pelaksanaan pilkada, terlebih pilpres masih cukup jauh hingga 2024. Dia meminta semua pihak menghormati setiap proses demokrasi, dan mengurangi hiruk pikuk dunia politik.\r\n\r\n\"Jadi saya tidak ingin komentar terkait masalah politik, apalagi pilkada, apalagi pilpres, terlebih lagi masih jauh, 2024,\" kata Riza di Jagakarsa, Jakarta Selatan seperti dikutip Detik.com, Sabtu (9/10).\r\n\r\nIa meminta semua pihak saat ini mendukung Jokowi, yang selama ini juga telah mendukung program di DKI Jakarta.\r\n\r\n\"Mari kita bekerja, mendukung Pak Jokowi dengan berbagai kebijakannya. Pemerintah pusat mendukung Pak Anies di Jakarta, membangun Jakarta. Mari kita dukung pemimpin-pemimpin di seluruh Indonesia,\" kata dia.\r\n\r\nHal itu disampaikan Riza merespons pernyataan Ketua DPRD DKI Jakarta Prasetio Edi Marsudi yang meminta Anies dan pendukungnya berhenti membuat narasi seolah-olah pemilu serentak 2024 sengaja dibuat untuk menjegal Anies.\r\n\r\nMenurut Pras, sapaan akrabnya, pelaksanaan pemilu serentak 2024 adalah amanat Undang-Undang Nomor 10 Tahun 2016 yang disahkan sebelum Anies menjadi gubernur.\r\n\r\nSebagai informasi, merujuk undang-undang tersebut, Anies akan mengakhiri masa jabatannya sebagai gubernur pada 2022. Sebab, pilkada baru akan digelar pada 2024 bersamaan dengan pileg dan pilpres. Untuk mengisi kekosongan posisi yang ditinggalkan, pemerintah akan menunjuk penjabat sementara.', '2021-10-10', 'https://akcdn.detik.net.id/visual/2021/05/17/wakil-gubernur-dki-jakarta-ahmad-riza-patria_169.jpeg?w=650');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `namaDepan` varchar(25) DEFAULT NULL,
  `namaBelakang` varchar(25) DEFAULT NULL,
  `userName` varchar(15) DEFAULT NULL,
  `tgl_lahir` date DEFAULT NULL,
  `jenisKelamin` char(6) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `foto` varchar(255) DEFAULT NULL,
  `type` char(6) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`namaDepan`, `namaBelakang`, `userName`, `tgl_lahir`, `jenisKelamin`, `id`, `password`, `foto`, `type`) VALUES
('HEHEHEHE', 'HAHAHAHah', '11', '2021-10-21', 'pria', '61606189e83b2', '$2y$10$xDPgFZ581Jmpo.zXeUJ2ZOB9NqJE8sWBRbRP.oVJNpHWGv7iyAQn6', 'foto-profil6160618a190ec.png', 'user'),
('Christine', 'Haha', 'christin', '2021-10-01', 'pria', '61619bda1051c', '$2y$10$6DvW9xZk4GdPncReqZ8fGe4K6ReXNs5a8J2UxKuJTihXhpLJS3T3S', 'foto-profil61619bda408d5.jpg', 'admin');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `berita`
--
ALTER TABLE `berita`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
